name: first yml
on:
  push:
    branches:
      - feature/dummy

jobs:
  build:
    runs-on: ubuntu

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Print Additional Info
      run: |
        echo "Additional information: sss" 

    - name: Run Tests
      run: pytest

    - name: Deploy
